spring:
  application:
    name: order-service
  boot:
    admin:
      client:
        url: http://localhost:8000/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

server:
  port: 1001
